name: Maven CI/CD

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build_and_test:
    env:
      ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
      HOTELIER_ACCESS_TOKEN: ${{ secrets.HOTELIER_ACCESS_TOKEN }}
      CUSTOMER_ACCESS_TOKEN: ${{ secrets.CUSTOMER_ACCESS_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clean
        run: mvn clean
      - name: Install
        run: mvn install
      - name: Build project with Maven
        run: mvn -B package --file pom.xml -e -X
      - name: Test project with Maven
        run: mvn test -f pom.xml